os: Visual Studio 2017

cache: c:\users\appveyor\clcache

environment:
  BOOST_ROOT: C:\Libraries\boost_1_67_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_67_0\lib64-msvc-14

init:
  - set PATH=c:\Python37;c:\Python37\Scripts;%PATH%
  - pip install clcache

before_build:
  - clcache -s

build_script:
  - md build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" ..
  - MSBuild ZentCash.sln /p:CLToolExe=clcache.exe /p:CLToolPath=c:\Python37\Scripts\ /p:Configuration=Release /m
  - src\Release\cryptotest.exe

after_build:
  - clcache -s
  - if not defined APPVEYOR_REPO_TAG_NAME (set APPVEYOR_REPO_TAG_NAME=%APPVEYOR_REPO_COMMIT%)
  - cd src\Release
  - mkdir ZentCash-%APPVEYOR_REPO_TAG_NAME%
  - copy *.exe ZentCash-%APPVEYOR_REPO_TAG_NAME%
  - copy ..\..\..\LICENSE ZentCash-%APPVEYOR_REPO_TAG_NAME%
  - 7z a ZentCash-%APPVEYOR_REPO_TAG_NAME%-windows.zip ZentCash-%APPVEYOR_REPO_TAG_NAME%
  - copy ZentCash-%APPVEYOR_REPO_TAG_NAME%-windows.zip ..\..\..\

artifacts:
  - path: ZentCash-$(APPVEYOR_REPO_TAG_NAME)-windows.zip
    name: ZentCashRelease

deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: HTw79Iizhy3FZaWMI6iPzvK+4m3QDspSp0WjGnt4Ws52HjazYzhms4MHIsK1z58k
    repository: ZentCashFoundation/ZentCash
    artifact: ZentCashRelease
    draft: false
    force_update: true
    on:
      branch: master
      appveyor_repo_tag: true
